# Generated by Django 6.0.1 on 2026-01-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meetings.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meetings.genre')),
                ('meeting_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meetings.meetingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('telegram_username', models.CharField(max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='meetings.meeting')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('meeting', 'phone_number'), name='unique_phone_per_meeting')],
            },
        ),
    ]
