# Generated by Django 4.2.27 on 2026-01-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='meetings.genre'),
            preserve_default=False,
        ),
    ]
